const products = [
	{
		name: `placenta vestibulum`,
		price: '$68.00',
		oldPrice: '$92.00',
		image: 'https://htmldemo.net/lukani/lukani/assets/img/product/product3.jpg',
		sale: '-77%',
		rate: 1,
	},
	{
		name: `sapient libero`,
		price: '$69.00',
		oldPrice: '$92.00',
		image: 'https://htmldemo.net/lukani/lukani/assets/img/product/product1.jpg',
		sale: '-77%',
		rate: 2,
	},
	{
		name: `adipiscing cercus`,
		price: '$68.00',
		oldPrice: '$92.00',
		image: 'https://htmldemo.net/lukani/lukani/assets/img/product/product2.jpg',
		sale: '-77%',
		rate: 3,
	},
	{
		name: `fringilla augur`,
		price: '$68.00',
		oldPrice: '$92.00',
		image: 'https://htmldemo.net/lukani/lukani/assets/img/product/product4.jpg',
		sale: '-77%',
		rate: 4,
	},
	{
		name: `massa poirot`,
		price: '$68.00',
		oldPrice: '$92.00',
		image: 'https://htmldemo.net/lukani/lukani/assets/img/product/product5.jpg',
		sale: '-77%',
		rate: 5,
	},
	{
		name: `Donees eu cook`,
		price: '$68.00',
		oldPrice: '$92.00',
		image: 'https://htmldemo.net/lukani/lukani/assets/img/product/product6.jpg',
		sale: '-77%',
		rate: 4,
	},
	{
		name: `placerat vestibulum`,
		price: '$68.00',
		oldPrice: '$92.00',
		image: 'https://htmldemo.net/lukani/lukani/assets/img/product/product7.jpg',
		sale: '-77%',
		rate: 4,
	},
	{
		name: `sapien libero`,
		price: '$69.00',
		oldPrice: '$92.00',
		image: 'https://htmldemo.net/lukani/lukani/assets/img/product/product8.jpg',
		sale: '-77%',
		rate: 4,
	},
	{
		name: `adipiscing curcus`,
		price: '$68.00',
		oldPrice: '$92.00',
		image: 'https://htmldemo.net/lukani/lukani/assets/img/product/product9.jpg',
		sale: '-77%',
		rate: 4,
	},
	{
		name: `fringilla augue`,
		price: '$68.00',
		oldPrice: '$92.00',
		image: 'https://htmldemo.net/lukani/lukani/assets/img/product/product10.jpg',
		sale: '-77%',
		rate: 4,
	},
	{
		name: `massa porror`,
		price: '$68.00',
		oldPrice: '$92.00',
		image: 'https://htmldemo.net/lukani/lukani/assets/img/product/product11.jpg',
		sale: '-77%',
		rate: 4,
	},
	{
		name: `Donec eu cook`,
		price: '$68.00',
		oldPrice: '$92.00',
		image: 'https://htmldemo.net/lukani/lukani/assets/img/product/product12.jpg',
		sale: '-77%',
		rate: 4,
	},
	{
		name: `placerat vestibulum`,
		price: '$68.00',
		oldPrice: '$92.00',
		image: 'https://htmldemo.net/lukani/lukani/assets/img/product/product13.jpg',
		sale: '-77%',
		rate: 4,
	},
	{
		name: `sapien libero`,
		price: '$69.00',
		oldPrice: '$92.00',
		image: 'https://htmldemo.net/lukani/lukani/assets/img/product/product1.jpg',
		sale: '-77%',
		rate: 4,
	},
	{
		name: `adipiscing curcus`,
		price: '$68.00',
		oldPrice: '$92.00',
		image: 'https://htmldemo.net/lukani/lukani/assets/img/product/product5.jpg',
		sale: '-77%',
		rate: 4,
	},
	{
		name: `fringilla augue`,
		price: '$68.00',
		oldPrice: '$92.00',
		image: 'https://htmldemo.net/lukani/lukani/assets/img/product/product6.jpg',
		sale: '-77%',
		rate: 4,
	},
	{
		name: `massa porror`,
		price: '$68.00',
		oldPrice: '$92.00',
		image: 'https://htmldemo.net/lukani/lukani/assets/img/product/product7.jpg',
		sale: '-77%',
		rate: 4,
	},
	{
		name: `Donec eu cook`,
		price: '$68.00',
		oldPrice: '$92.00',
		image: 'https://htmldemo.net/lukani/lukani/assets/img/product/product2.jpg',
		sale: '-77%',
		rate: 4,
	},
];
export default products;
